FROM prairielearn/centos7-base

RUN yum -y install epel-release \
        && yum -y install clang \
        && yum -y install make \
        && yum -y install subversion \
        && yum -y install gcc \
        && yum -y install gcc-c++ 

#ENTRYPOINT ["bash"]
